[DOC] Setup tutorial
AetherModel/aetherpy pull request #4
Opened 2021-09-21 16:01 UTC by qalshidi

In regards to #3 .

Add a simple tutorial on a workflow setup for aetherpy in `CONTRIBUTING.md`

2021-09-23 16:15 UTC, aburrell requested changes

2021-09-23 16:15 UTC, aburrell commented on CONTRIBUTING.md
> +python setup.py install --user
```suggestion
python setup.py develop --user
```

2021-09-23 16:15 UTC, aburrell commented on CONTRIBUTING.md
> +Or you may install it to test how it may work globally:
```suggestion
Or you may install it to test how it may work globally while you continue to develop the code:
```

2021-09-23 17:00 UTC, qalshidi reviewed
Thank you for the suggestion

2021-11-05 20:21 UTC, aburrell approved these changes
Don't forget to re-request a review when you're ready for one.

2021-11-17 16:00 UTC, merged